### ISSUE TITLE
spawned realm's global

### ISSUE THREAD

**Issue by caridy** [tc39/proposal-ses#19]
In the summary, when describing the steps, I see:

> The spawn method makes (1) a new lightweight child realm with (2) a new _global_ inheriting from its parent's _global_...

That doesn't seems right at first glance. Does this means that any global variable defined in the parent realm will be accessible in the spawned realm? e.g.:

```
sharedRoot.eval('function foo(value) { console.log(value); }');
const childRealm = sharedRoot.spawn({});
sharedRoot.eval('foo(1)'); // should this yield 1 or throw?
```

/cc @erights

**Comment by benjamingr** [comment]
I believe it does - yes. Why is that a problem?

(That is, it should log 1)

**Comment by caridy** [comment]
@benjamingr I just wanted to be sure! It is all clear now that I have started to flesh out the [Realm API](https://github.com/caridy/proposal-realms), the exhibited behavior is a result of the inheritance described by:

```
sharedRoot.global === Object.getPrototypeOf(childRealm.global)
```

I think we are good, closing this one.
