### ISSUE TITLE
Why non-ascii characters in spec as rendered into html

### ISSUE THREAD

**Issue by erights** [tc39/proposal-ses#22]
Hi @caridy and @bterlson , I notice that https://raw.githubusercontent.com/FUDCo/proposal-frozen-realms/master/index.html contains several occurrences of the "◢" \u25e2 black lower right triangle character, but that these do not appear in the spec source at https://raw.githubusercontent.com/FUDCo/proposal-frozen-realms/master/spec/index.emu . Are these introduced for some reason by the process of generating the html from the source? Why?

**Comment by caridy** [comment]
@erights this is introduced by ecmarkup when rendering the left hand side index menu to html, to signal expand vs collapsed options in the menu. I think @bterlson is using that character, rotating it 45 degrees with css, you can see it in action here: https://rawgit.com/FUDCo/proposal-frozen-realms/master/index.html or in any of our specs.

**Comment by caridy** [comment]
btw, I haven't finish with the build steps, but eventually the HTML will be pushed into gh-pages branch, will work on that soon, for now focus on the spec text for the next meeting.

**Comment by caridy** [comment]
@erights if you feel we should not use that characters, we can open an new issue for [ecmarkup](https://github.com/bterlson/ecmarkup/issues/new). closing this one.

**Comment by erights** [comment]
Hi @caridy with your explanation, closing is fine. I just had no idea why it was there. Thanks.
