### ISSUE TITLE
Nomadic bind

### ISSUE THREAD

**Issue by erights** [tc39/proposal-ses#25]
If we think of the `.then` operator as like a _monadic bind_, we can think of the mobile-code supporting `.there` operator as like a _nomadic bind_ ;).

**Comment by benjamingr** [comment]
What?

**Comment by erights** [comment]
This is a dangerous analogy because it reinforces the misunderstanding that `then` and Promises are monad-like. They are more concurrent-logic-variable-like. The monad analogy has some truth to it, but altogether has caused much more confusion than clarity.

**Comment by benjamingr** [comment]
`then` _is_ a monadic bind if we only allow the `Promise<A>.(A -> Promise<B>) -> Promise<B>` variant of it (that is, only flatMap and no exceptions).

Still, what's `there`?

**Comment by erights** [comment]
@benjamingr

The pun was too good to remain not posted anywhere. Just a pun. Hence the smiley and immediate closing.

**Comment by erights** [comment]
The map vs flatmap issue is the reason why the monad analogy both had some truth to it and was so unfortunate. It caused endless unnecessary confusion and argument, which, thankfully, is now mostly over.

**Comment by erights** [comment]
> Still, what's `there`?

https://github.com/FUDCo/proposal-frozen-realms#mobile-code-example

**Comment by benjamingr** [comment]
I'm confused, didn't you come up with and use promises to begin with for this reason :P?

Wasn't the point to model RPS so that `then` abstracts the fact an operation works remotely in the first place? 

(The pun is cute though)

**Comment by erights** [comment]
Both `.then` and `.there` operate on promises to remote objects. However, then do so differently. Only `.there` moves the onSuccess callback's code to the remote site. Thus, only `.there` imposes a restriction that this callback must be a closed function.

**Comment by erights** [comment]
What is "RPS"?

**Comment by benjamingr** [comment]
RPS is RPC except I missed the C by two keys in my keyboard. 

The restriction on closed-function seems arbitrary since we can't do better by the way. Other languages (namely C#) solve this by capturing and passing the closure context explicitly and giving access to it (either by value or reference).

I guess "arbitrary" is probably "necessary because of the language's lack of explicit ability to give closure access to stuff".

The pun is nice though, a nomadic function is one that can be moved and evaluated elsewhere :)

**Comment by erights** [comment]
The important remote promise operations are the remote-message-send operations which Q and Q-connection support but which are not yet standard. These are necessary for promise pipelining. `.then` cannot support promise pipelining because it must force a round trip, and the onSuccess callback always executes at the requesting site. `.there` does support pipelining, but only for sites willing to do a confined evaluation of client code. Due to the availability issues mentioned in #7 , this will be a small subset of the sites that could support promise pipelining.

**Comment by erights** [comment]
Most of the credit for the pun goes to @FUDCo .

**Comment by erights** [comment]
I did not know that C# supported that. Link to explanation? Thanks.

**Comment by benjamingr** [comment]
> These are necessary for promise pipelining. .then cannot support promise pipelining because it must force a round trip, and the onSuccess callback always executes at the requesting site.

I'm starting to feel like eager `then` is really causing us a lot of work with scoping. One of the things that bother me the most about promises is the lack of the ability to confine the execution of a chain. That is, I can't say "all the promises that didn't resolve by the end of this action that were created inside it - maybe Zones will help with that but it's definitely causing a lot of issues in making promises first-class in Node.

**Comment by benjamingr** [comment]
> I did not know that C# supported that. Link to explanation? Thanks.

Well, in C# you can do:

``` cs
var l = new List<int>{1,2,3};
var i = 5;
var l2 = l.Select(x => x * i); // .map, so far ez
var db = getEntityFrameworkHandle(); // or another LINQ provider
var l3 = l2.NumbersTable.Select(x => x * i).ToList(); // x * i gets compiled to SQL by the LINQ provider
```

I think @spion did some research on how this is done and might be able to shed light on the issue.

**Comment by erights** [comment]
> // x \* i gets compiled to SQL by the LINQ provider

Whoa, how that does happen? Does the LINQ provider transform the source code above? If so, what statically marks this code as special so that something knows to translate it? 

If not, then is it in the implementation of `.Select` that it somehow translates the closure it receives? If so, then how does this magic within `.Select` get access to the caller's `i` location?

**Comment by benjamingr** [comment]
@erights this is how a LINQ provider do. You get a generated class for the closure which you can access in a LINQ provider. (The compiler generates the class and you can access its properties). This lets you pass those values to the RPC and have a regular function do what we in JS only do with "nomadic" ones.

Your provider gets a limited subset of functions (expression arrows) as input as a syntax tree and your provider transforms them to whatever you want (LINQ to RavenDB creates ravendb queries, LINQ to Entities does SQL, LINQ to XML does xpath and so on). The most basic is LINQ to object that just works on objects and is much simpler than the others - it works on IEnumerables and not IQueryables.

Pinging @linkgoron who explained some details to me right now and might want to add someting and also see https://msdn.microsoft.com/en-us/library/bb546158(v=vs.110).aspx

**Comment by Linkgoron** [comment]
If you're interested I created a gist

https://gist.github.com/Linkgoron/a709df98ebec21a88529dcc044991aa6

I used ilspy to get the compiled code.
Note that I'm using .net 4.6.1 as the generated code is a bit different than 4.5 code.

Edit:
Also added a regular function instead of an expression, for comparison.

**Comment by spion** [comment]
I was just toying with a Babel plugin that allows closure access for arrow functions:

https://gist.github.com/spion/adc5b0110f9466efc0a2

Of course, if we were to really implement this we'd probably need some sort of special function syntax. The plugin also assumes static scope (so "use strict" is required)
