### ISSUE TITLE
What about the Realms API proposal?

### ISSUE THREAD

**Issue by erights** [tc39/proposal-ses#9]
Attn @dherman

We explicitly postponed the [Realm API proposal](https://gist.github.com/dherman/7568885) from ES6 in order to better understand its security properties before proceeding towards standardization. The test we all agreed to try was to layer SES on it to see how it went, and to attack the result. This was in terms of the SES-shim at the time since there was no other SES then. Now that we have a concrete and much simpler notion of what builtin SES would be like, we should revisit this soon.

**Comment by caridy** [comment]
During last meeting, we decided to revive the Realms API proposal, it is still stage 0, but we are actively working on it. Details are here: https://github.com/caridy/proposal-realms

Closing this in favor of tracking the realms API proposal on its own repo.
